/****************************************
 BCG DATA EXPORT SCRIPT
 
 VERSION: 1.0
 DESCRIPTION: 
    CONSOLIDATING ALL DATA EXPORT FROM 
    CSMS INTO A SINGLE SCRIPT FOR 
    EASIER AND EFFORTLESS FILE GENERATION
    
 AUTHOR: ALBERT XU
 DATE: 09-FEB-2018
 ****************************************/

/****************************************
 SCRIPT VARIABLES. DO NOT EDIT IF UNSURE
 ****************************************/

-- THIS SECTION IS LEFT BLANK INTENTIONALLY
 
/****************************************
 PARAMETERS SETUP
 ****************************************/
DEFINE V_OUTPUT_FOLDER = 'D:\Users\alxu\ONEDRI~1\SHARED~1\BCG\'

DEFINE V_BCG_STARTDATE = '01-OCT-2015'
DEFINE V_BCG_ENDDATE = '30-SEP-2017'

-- TO EXCLUDE JASONS, MARKETPLACE, AND CSONLINE SALES
DEFINE V_EXCLUDE_STORES_LIST = '''071'',''030'',''031'',''063'',''084'',''086'',''088'',''129'',''134'''

-- NEW ITEM CRITERIA (IN MONTHS) PARAMETER
DEFINE V_NEW_ITEM_MONTHS = '3'

/****************************************
 ALL NON-CONCESS ITEMS SKU ATTRIBUTES EXPORT (EXCLUDE NEW ITEMS)
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_001_NON_CONCESS_ITEM_MASTER
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_001_NON_CONCESS_ITEM_MASTER.CSV
SPOOL "&&V_FILENAME"
/
SELECT  I.ITEM_CD "SKU CODE",
        I.BRND_ENAME "BRAND NAME",
        I.ITEM_CNAME "SKU DESCRIPTION",
        I.CSHR_KIND "DEPT CODE",
        I.BIG_KIND "CAT CODE",
        I.MDL_KIND "SUBCAT CODE",
        I.ITEM_LE "LENGTH",
        I.ITEM_WI "WIDTH",
        I.ITEM_HI "HEIGHT", 
        I.ITEM_WT "WEIGHT",
        I.PROM_ONE_CD "PROMO_ITEM",
        I.SEASON_FLG,
        DECODE(I.CONTROL_FLG,'D', 'DELETED', 'T', 'STOCKOUT', NULL) "PRODUCT STATUS",
        (SELECT MAX(BAR_CODE) FROM SMGR.BAR_TBL BT2 WHERE CREATE_DATE=(SELECT MAX(CREATE_DATE) FROM SMGR.BAR_TBL BT WHERE BT.ITEM_CD=I.ITEM_CD) AND BT2.ITEM_CD=I.ITEM_CD) "BARCODE",
        I.PROD_CHAR AS "CHAR",
        (SELECT SUBSTR(PARAM_DESC,1,30) PARAM_NAME FROM SMGR.PARAM_TBL PT WHERE PT.PARAM_ID = 'ITEMPRDCHR' AND PT.PARAM_CD=I.PROD_CHAR) "CHAR DESCRIPTION",
        I.ITEM_CHAR "COO",
        CM.COUNTRY_NM "COO DESC",
        I.CREATE_DATE "CREATION DATE",
        I.ODR_CTL_FLG "FLG",
        I.CR_DEPT_LEVEL "GRADING CD",
        (SELECT ASSORT_SUB_NM FROM SMGR.CR_ASSORT_D GD WHERE GD.ASSORT_SUB_CD=I.CR_DEPT_LEVEL) "GRADING DESC", 
        I.RETURN_CD "GRN",
        I.IL,
        I.ITEM_PACK_NUM "OP",
        I.PNT_ITEM_CD "PARENT ITEM CODE",
        I.CONTROL_DATE "PRODUCT STATUS DATE",
        I.ITEM_SIZE "SIZE",
        I.ITEM_UNIT "UNIT"
FROM SMGR.ITEM I
LEFT JOIN SMGR.COUNTRY_M CM ON CM.COUNTRY_CD=I.ITEM_CHAR
WHERE   LENGTH(I.ITEM_CD)='6' -- Filter legacy items that are not of 6 digits length
        AND NOT (NVL(I.CONTROL_FLG,'A')='D' AND I.CONTROL_DATE<ADD_MONTHS('&&V_BCG_STARTDATE',-12)) -- Filter items that are deleted more than 12 months from the start of the BCG review period
ORDER BY I.ITEM_CD
/
SPOOL OFF
/

/****************************************
 ALL CONCESS ITEMS SKU ATTRIBUTES EXPORT (EXCLUDE NEW ITEMS)
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_002_CONCESS_ITEM_MASTER
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_002_CONCESS_ITEM_MASTER.CSV
SPOOL "&&V_FILENAME"
/
SELECT  ITEM_CD "SKU CODE",
        '' "BRAND NAME",
        DESCRIPTION "SKU DESCRIPTION",
        CSHR_KIND "DEPT CODE",
        BIG_KIND "CAT CODE",
        MDL_KIND "SUBCAT CODE",
        '' "LENGTH",
        '' "WIDTH",
        '' "HEIGHT", 
        '' "WEIGHT",
        '' "PROMO_ITEM",
        '' "SEASON_FLG",      
        DECODE(CONTROL_FLG,'D', 'DELETED', 'T', 'STOCKOUT', NULL) "PRODUCT STATUS",
        '' "BARCODE",
        '' "CHAR",
        '' "CHAR DESCRIPTION",
        '' "COO",
        '' "COO DESC",
        I.CREATE_DATE "CREATION DATE",
        '' "FLG",
        '' "GRADING CD",
        '' "GRADING DESC",
        '' "GRN",
        '' "IL",
        '' "OP",
        '' "PARENT ITEM CODE",
        I.DELETE_DATE "PRODUCT STATUS DATE",
        '' "SIZE",
        '' "UNIT"
FROM SMGR.ITEM_DEPT I
WHERE   LENGTH(ITEM_CD)='6' -- Filter legacy items that are not of 6 digits length
        AND NOT (NVL(I.CONTROL_FLG,'A')='D' AND I.DELETE_DATE<ADD_MONTHS('&&V_BCG_STARTDATE',-12)) -- Filter items that are deleted more than 12 months from the start of the BCG review period
ORDER BY ITEM_CD
/
SPOOL OFF
/

/****************************************
 SKU VENDOR MAPPING EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_003_SKU_VENDOR_MAPPING
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_003_SKU_VENDOR_MAPPING.CSV
SPOOL "&&V_FILENAME"
/
SELECT DISTINCT CIM.BAN_ITEM_CD "SKU CODE",
        VI.VNDR_ID "VENDOR CODE",
        V.VNDR_CNAME
FROM SMGR.ITEM I
JOIN SMGR.CMS_ITEM_MAP@MDFSG_H CIM ON (CIM.BAN_ITEM_CD=I.ITEM_CD AND CIM.BANNER='CS')
LEFT JOIN SMGR.VNDR_ITEM@MDFSG_H VI ON (CIM.CMS_ITEM_CD=VI.ITEM_CD)
LEFT JOIN SMGR.VNDR@MDFSG_H V ON (V.VNDR_ID=VI.VNDR_ID AND V.VNDR_SUB_ID=VI.VNDR_SUB_ID)
WHERE   VI.PMY_FLG='Y' AND VI.BAN_CS='Y'
        AND LENGTH(I.ITEM_CD)='6' -- Filter legacy items that are not of 6 digits length
        AND NOT (NVL(I.CONTROL_FLG,'A')='D' AND I.CONTROL_DATE<ADD_MONTHS('&&V_BCG_STARTDATE',-12)) -- Filter items that are deleted more than 12 months from the start of the BCG review period
        AND GREATEST(VI.CREATE_DATE,NVL(VI.UPDATE_DATE,VI.CREATE_DATE))=
        (
            SELECT MAX(GREATEST(VI2.CREATE_DATE, NVL(VI2.UPDATE_DATE,VI2.CREATE_DATE))) VNDR_LATEST_DATE
            FROM SMGR.VNDR_ITEM@MDFSG_H VI2
            WHERE   VI2.PMY_FLG='Y' 
                    AND VI2.BAN_CS='Y'
                    AND VI2.ITEM_CD=VI.ITEM_CD
        ) 
UNION
-- CSMS
SELECT DISTINCT I.ITEM_CD "SKU CODE",
        VI.VNDR_ID "VENDOR CODE",
        V.VNDR_CNAME 
FROM SMGR.ITEM I
LEFT JOIN SMGR.VNDR_ITEM VI ON (I.ITEM_CD=VI.ITEM_CD)
LEFT JOIN SMGR.VNDR V ON (V.VNDR_ID=VI.VNDR_ID AND V.VNDR_SUB_ID=VI.VNDR_SUB_ID)
WHERE   LENGTH(I.ITEM_CD)='6' -- Filter legacy items that are not of 6 digits length
        AND NOT (NVL(I.CONTROL_FLG,'A')='D' AND I.CONTROL_DATE<ADD_MONTHS('&&V_BCG_STARTDATE',-12)) -- Filter items that are deleted more than 12 months from the start of the BCG review period
        AND NOT EXISTS (SELECT BAN_ITEM_CD FROM SMGR.CMS_ITEM_MAP@MDFSG_H CIM WHERE CIM.BANNER='CS' AND CIM.BAN_ITEM_CD=I.ITEM_CD)
        AND GREATEST(VI.CREATE_DATE,NVL(VI.UPDATE_DATE,VI.CREATE_DATE))=
        (
            SELECT MAX(GREATEST(VI2.CREATE_DATE, NVL(VI2.UPDATE_DATE,VI2.CREATE_DATE))) VNDR_LATEST_DATE
            FROM SMGR.VNDR_ITEM VI2
            WHERE   VI.PMY_FLG='Y'
                    AND VI2.ITEM_CD=VI.ITEM_CD
        )
UNION
-- CONCESS ITEMS
SELECT DISTINCT ID.ITEM_CD "SKU CODE",
        ID.VNDR_ID "VENDOR CODE",
        V.VNDR_CNAME
FROM SMGR.ITEM_DEPT ID
LEFT JOIN SMGR.VNDR V ON (V.VNDR_ID=ID.VNDR_ID AND V.VNDR_SUB_ID=ID.VNDR_SUB_ID)
WHERE   LENGTH(ID.ITEM_CD)='6' -- Filter legacy items that are not of 6 digits length
        --AND NOT (NVL(ID.CONTROL_FLG,'A')='D' AND ID.DELETE_DATE<ADD_MONTHS('&&V_BCG_STARTDATE',-12)) --Revamped logic on detecting DELETED items due to dirty data.............
        AND (ID.DELETE_DATE IS NULL OR ID.DELETE_DATE<ADD_MONTHS('&&V_BCG_STARTDATE',-12))
/
SPOOL OFF
/

/****************************************
 SKU BARCODE MAPPING EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_004_SKU_BARCODE_MAPPING
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_004_SKU_BARCODE_MAPPING.CSV
SPOOL "&&V_FILENAME"
/
SELECT  ITEM_CD "SKU CODE",
        BAR_CODE "BARCODE"
FROM SMGR.BAR_TBL
ORDER BY ITEM_CD
/
SPOOL OFF
/

/****************************************
 FULL DEPARTMENT MASTER EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_005_FULL_DEPARTMENT_MASTER
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_005_FULL_DEPARTMENT_MASTER.CSV
SPOOL "&&V_FILENAME"
/
SELECT  CSHR_KIND "DEPT CODE",
        CDSCR "DESCRIPTION"
FROM SMGR.CSHR
ORDER BY CSHR_KIND
/
SPOOL OFF
/

/****************************************
 FULL CATEGORY MASTER EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_006_FULL_CATEGORY_MASTER
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_006_FULL_CATEGORY_MASTER.CSV
SPOOL "&&V_FILENAME"
/
SELECT  CSHR_KIND "DEPT CODE",
        BIG_KIND "CAT CODE",
        CDSCR "DESCRIPTION"
FROM SMGR.BIGK
ORDER BY CSHR_KIND, BIG_KIND
/
SPOOL OFF
/

/****************************************
 FULL SUB CATEGORY MASTER EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_007_FULL_SUB_CATEGORY_MASTER
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_007_FULL_SUB_CATEGORY_MASTER.CSV
SPOOL "&&V_FILENAME"
/
SELECT  BIG_KIND "CAT CODE",
        MDL_KIND "SUBCAT CODE",
        CDSCR "DESCRIPTION"
FROM SMGR.MDLK
ORDER BY BIG_KIND, MDL_KIND
/
SPOOL OFF
/

/****************************************
 SKU PRIVATE LABEL MAPPING EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_008_SKU_PRIVATE_LABEL_MAPPING
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_008_SKU_PRIVATE_LABEL_MAPPING.CSV
SPOOL "&&V_FILENAME"
/
SELECT  ITEM_CD "SKU CODE",
        NVL(HBRAND_FLG,'N') "HOUSEBRAND"
FROM    SMGR.ITEM I
WHERE   LENGTH(I.ITEM_CD)='6' -- Filter legacy items that are not of 6 digits length
        AND NOT (NVL(I.CONTROL_FLG,'A')='D' AND I.CONTROL_DATE<ADD_MONTHS('&&V_BCG_STARTDATE',-12)) -- Filter items that are deleted more than 12 months from the start of the BCG review period
ORDER BY ITEM_CD
/
SPOOL OFF
/

/****************************************
 FULL STORE MASTER EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_009_FULL_STORE_MASTER
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_009_FULL_STORE_MASTER.CSV
SPOOL "&&V_FILENAME"
/
SELECT  AREA_SUB_ID "STORE CODE",
        'OUTLET' "CHANNEL",
        TRIM(DEPT_CNAME) "STORE NAME",
        TRUNC(OPEN_DATE) "OPEN DATE",
        DECODE(CLOSE_DATE, NULL, 'YES','NO') "OPEN",
        ADDRS_LINE4 "ZIP",
        STORE_SIZE "STORE SIZE",
        STR_CLUSTER "STORE CLUSTER",
        '' "OM",
        AREA_CODE "AREA",
        '' "CLUSTER",
        '' "WHO WE ARE SERVING?",
        '' "INCOME",
        '' "DWELLING",
        '' "DESTINATION",
        '' "NET TRADING AREA (A)",
        '' "BACK END AREA (B)",
        '' "SUBTOTAL (A)+(B)",
        '' "CONCESS AREA (C)",
        '' "COMMON AREA (D)", 
        '' "TOTAL GROSS LEASED AREA",
        '' "SCOPE",
        TRIM(DEPT_CADDRS)||' '||TRIM(ADDRS_LINE2)||' '||TRIM(ADDRS_LINE3)||' ' ||TRIM(ADDRS_LINE4) "ADDRESS",
        '' "OPERATING HOURS",
        DEPT_TEL "PHONE",
        '' "FAX",
        '' "LATITUDE",
        '' "LONGITUDE"
FROM    SMGR.DEPT
WHERE   BANNER_CD IN ('CS','UP')
        AND NVL(OPEN_DATE,SYSDATE)<='&&V_BCG_ENDDATE'
        AND NVL(CLOSE_DATE,SYSDATE)>='&&V_BCG_STARTDATE'
ORDER BY AREA_SUB_ID
/
SPOOL OFF
/

/****************************************
 STORE REGION MAPPING EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_010_STORE_REGION_MAPPING
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_010_STORE_REGION_MAPPING.CSV
SPOOL "&&V_FILENAME"
/
SELECT  DEPT_CNAME "STORE NAME",
        AREA_SUB_ID "STORE CODE",
        DEPT_CABB "ABBREVIATION",
        AREA_CODE "AREA",
        '' "OM",
        AREA_ID "PRICE REGION"
FROM SMGR.DEPT
WHERE   BANNER_CD IN ('CS','UP')
        AND NVL(OPEN_DATE,SYSDATE)<='&&V_BCG_ENDDATE'
        AND NVL(CLOSE_DATE,SYSDATE)>='&&V_BCG_STARTDATE'
ORDER BY AREA_SUB_ID
/
SPOOL OFF
/

/****************************************
 SKU COST CURRENT EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_011_SKU_COST_CURRENT
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_011_SKU_COST_CURRENT.CSV
SPOOL "&&V_FILENAME"
/
SELECT  ITEM_CD,
        AREA_ID,
        AREA_SUB_ID,
        BGN_DATE,
        END_DATE,
        NRML_COST,
        NRML_PRICE,
        CTN_COST
FROM SMGR.COST_CUR
ORDER BY ITEM_CD, AREA_ID
/
SPOOL OFF
/

/****************************************
 SKU COST HISTORY EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_012_SKU_COST_HISTORY
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_012_SKU_COST_HISTORY.CSV
SPOOL "&&V_FILENAME"
/
SELECT  ITEM_CD,
        AREA_ID,
        AREA_SUB_ID,
        BGN_DATE,
        END_DATE,
        NRML_COST,
        NRML_PRICE,
        CTN_COST
FROM SMGR.COST_HIS
WHERE   NOT(BGN_DATE < '&&V_BCG_STARTDATE' AND END_DATE < '&&V_BCG_STARTDATE') -- Filter records that begins and ends BEFORE the BCG review period
        AND NOT(BGN_DATE > '&&V_BCG_ENDDATE' AND END_DATE > '&&V_BCG_ENDDATE') -- Filter records that begins and ends AFTER the BCG review period
ORDER BY ITEM_CD, AREA_ID, ITEM_CD, BGN_DATE, END_DATE
/
SPOOL OFF
/

/****************************************
 GP FOR CONCESS ITEMS EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_013_GP_FOR_CONCESS
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_013_GP_FOR_CONCESS.CSV
SPOOL "&&V_FILENAME"
/
SELECT  ITEM_CD,
        AREA_ID,
        AREA_SUB_ID,
        BGN_DATE,
        END_DATE,
        GP_RATE
FROM SMGR.GP_CUR
WHERE   NOT(BGN_DATE < '&&V_BCG_STARTDATE' AND END_DATE < '&&V_BCG_STARTDATE') -- Filter records that begins and ends BEFORE the BCG review period
        AND NOT(BGN_DATE > '&&V_BCG_ENDDATE' AND END_DATE > '&&V_BCG_ENDDATE') -- Filter records that begins and ends AFTER the BCG review period
ORDER BY ITEM_CD, BGN_DATE, END_DATE
/
SPOOL OFF
/

/****************************************
 ADHOC INCOME EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_014_ADHOC_INCOME_EXPORT
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_014_ADHOC_INCOME_EXPORT.CSV
SPOOL "&&V_FILENAME"
/
SELECT  ACCOUNT_DATE, 
        BGN_DATE, 
        END_DATE, 
        VNDR_ID AS "VENDOR CODE", 
        ITEM_CD AS "ITEM CODE", 
        NOTE_DESC,
        (SELECT TERM_CAT_CDSCR FROM SMGR.DBCAT WHERE TERM_CAT=S.TERM_CAT) AS "TT DESCRIPTION", 
        DBNTE_AMOUNT AS "TRADE AMOUNT", 
        EXTRACT(YEAR FROM ACCOUNT_DATE) AS "YEAR"
FROM SMGR.MDBNTE M, SMGR.SDBNTE S
WHERE USER_NAME <> 'AUTOPDDN'
AND M.SQL_NO=S.SQL_NO
AND ACCOUNT_DATE BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE' 
AND DBNTE_AMOUNT >0
--AND TERM_CAT NOT IN ('K','I')
UNION
SELECT  ACCOUNT_DATE, 
        BGN_DATE, 
        END_DATE, 
        VNDR_ID AS "VENDOR CODE", 
        (SELECT BAN_ITEM_CD FROM SMGR.CMS_ITEM_MAP@MDFSG_H WHERE BANNER='CS' AND CMS_ITEM_CD=S.ITEM_CD) AS "ITEM CODE", 
        NOTE_DESC,
        (SELECT TERM_CAT_CDSCR FROM SMGR.DBCAT@MDFSG_H WHERE TERM_CAT=S.TERM_CAT) AS "TT DESCRIPTION", 
        DBNTE_AMOUNT AS "TRADE AMOUNT", 
        EXTRACT(YEAR FROM ACCOUNT_DATE) AS "YEAR"
FROM SMGR.MDBNTE@MDFSG_H M, SMGR.SDBNTE@MDFSG_H S
WHERE USER_NAME <> 'AUTOPDDN'
AND M.SQL_NO=S.SQL_NO
AND ACCOUNT_DATE BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE' 
AND DBNTE_AMOUNT >0
--AND TERM_CAT NOT IN ('K','I')
AND AREA_SUB_ID = 'BUYCS'
/
SPOOL OFF
/

/****************************************
 PD EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_015_PD_EXPORT
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_015_PD_EXPORT.CSV
SPOOL "&&V_FILENAME"
/
/*
SELECT  ACCOUNT_DATE, 
        BGN_DATE, 
        END_DATE, 
        VNDR_ID AS "VENDOR CODE", 
        ITEM_CD AS "ITEM CODE", 
        NOTE_DESC,
        (SELECT TERM_CAT_CDSCR FROM SMGR.DBCAT WHERE TERM_CAT=S.TERM_CAT) AS "TT DESCRIPTION", 
        DBNTE_AMOUNT AS "TRADE AMOUNT", 
        EXTRACT(YEAR FROM ACCOUNT_DATE) AS "YEAR"
FROM SMGR.MDBNTE M, SMGR.SDBNTE S
WHERE USER_NAME = 'AUTOPDDN'
AND M.SQL_NO=S.SQL_NO
AND ACCOUNT_DATE BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE' 
AND DBNTE_AMOUNT >0
--AND TERM_CAT NOT IN ('K','I')
UNION
SELECT  ACCOUNT_DATE, 
        BGN_DATE, 
        END_DATE, 
        VNDR_ID AS "VENDOR CODE", 
        (SELECT BAN_ITEM_CD FROM SMGR.CMS_ITEM_MAP@MDFSG_H WHERE BANNER='CS' AND CMS_ITEM_CD=S.ITEM_CD) AS "ITEM CODE", 
        NOTE_DESC,
        (SELECT TERM_CAT_CDSCR FROM SMGR.DBCAT@MDFSG_H WHERE TERM_CAT=S.TERM_CAT) AS "TT DESCRIPTION", 
        DBNTE_AMOUNT AS "TRADE AMOUNT", 
        EXTRACT(YEAR FROM ACCOUNT_DATE) AS "YEAR"
FROM SMGR.MDBNTE@MDFSG_H M, SMGR.SDBNTE@MDFSG_H S
WHERE USER_NAME = 'AUTOPDDN'
AND M.SQL_NO=S.SQL_NO
AND ACCOUNT_DATE BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE' 
AND DBNTE_AMOUNT >0
--AND TERM_CAT NOT IN ('K','I')
AND AREA_SUB_ID = 'BUYCS'
*/
SELECT YEAR, MONTH, "VENDOR CODE", "ITEM CODE", "TT DESCRIPTION", SUM("TRADE AMOUNT") AS "TRADE AMOUNT", SUM(QTY) AS "QTY"
FROM 
(
SELECT  TO_CHAR(ACCOUNT_DATE, 'YYYY') AS "YEAR",
        TO_CHAR(ACCOUNT_DATE, 'MM') AS "MONTH",
        VNDR_ID AS "VENDOR CODE", 
        ITEM_CD AS "ITEM CODE", 
        TRIM((SELECT TERM_CAT_CDSCR FROM SMGR.DBCAT WHERE TERM_CAT=S.TERM_CAT)) AS "TT DESCRIPTION", 
        SUM(DBNTE_AMOUNT) AS "TRADE AMOUNT",
        SUM(SUBSTR(NOTE_DESC,(INSTR(UPPER(NOTE_DESC),'QTY ',1,1)+4),(INSTR(UPPER(NOTE_DESC),' ',INSTR(UPPER(NOTE_DESC),'QTY ',1,1)+4,1)-(INSTR(UPPER(NOTE_DESC),'QTY ',1,1)+4)))) "QTY"
FROM SMGR.MDBNTE M, SMGR.SDBNTE S
WHERE USER_NAME = 'AUTOPDDN'
AND M.SQL_NO=S.SQL_NO
AND ACCOUNT_DATE BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE' 
AND DBNTE_AMOUNT >0
GROUP BY TO_CHAR(ACCOUNT_DATE, 'YYYY'), TO_CHAR(ACCOUNT_DATE, 'MM'), VNDR_ID, ITEM_CD, TERM_CAT
UNION
SELECT  TO_CHAR(M.ACCOUNT_DATE, 'YYYY') AS "YEAR",
        TO_CHAR(M.ACCOUNT_DATE, 'MM') AS "MONTH",
        M.VNDR_ID AS "VENDOR CODE", 
        I.BAN_ITEM_CD AS "ITEM CODE", 
        TRIM((SELECT TERM_CAT_CDSCR FROM SMGR.DBCAT@MDFSG_H WHERE TERM_CAT=S.TERM_CAT)) AS "TT DESCRIPTION", 
        SUM(S.DBNTE_AMOUNT) AS "TRADE AMOUNT", 
        SUM(SUBSTR(NOTE_DESC,(INSTR(UPPER(NOTE_DESC),'QTY ',1,1)+4),(INSTR(UPPER(NOTE_DESC),' ',INSTR(UPPER(NOTE_DESC),'QTY ',1,1)+4,1)-(INSTR(UPPER(NOTE_DESC),'QTY ',1,1)+4)))) "QTY"
FROM SMGR.MDBNTE@MDFSG_H M, SMGR.SDBNTE@MDFSG_H S
JOIN SMGR.CMS_ITEM_MAP@MDFSG_H I ON I.BANNER='CS' AND I.CMS_ITEM_CD=S.ITEM_CD
WHERE M.USER_NAME = 'AUTOPDDN'
AND M.SQL_NO=S.SQL_NO
AND M.ACCOUNT_DATE BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE' 
AND S.DBNTE_AMOUNT >0
AND M.AREA_SUB_ID = 'BUYCS'
GROUP BY TO_CHAR(M.ACCOUNT_DATE, 'YYYY'), TO_CHAR(M.ACCOUNT_DATE, 'MM'), M.VNDR_ID, I.BAN_ITEM_CD, S.TERM_CAT
)
GROUP BY YEAR, MONTH, "VENDOR CODE", "ITEM CODE", "TT DESCRIPTION"
ORDER BY YEAR, MONTH, "VENDOR CODE", "ITEM CODE", "TT DESCRIPTION"
/
SPOOL OFF
/

/****************************************
 TT EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_016_TT_EXPORT
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_016_TT_EXPORT.CSV
SPOOL "&&V_FILENAME"
/
SELECT  T.ACCOUNT_DATE,
        T.VNDR_ID,
        (SELECT TT_CSDCR FROM SMGR.TTCODE
		 WHERE TT_CODE||TT_FREQ||TT_PYMT=T.TT_CODE||T.TT_FREQ||T.TT_PYMT ) TT_DESCRIPTION, 
        NVL(T.TRADE_AMOUNT,0) - NVL(S.TRADE_AMOUNT,0) TRADE_AMOUNT
FROM    SMGR.TRADE T, SMGR.TRADE_SNS S
WHERE   T.VNDR_ID = S.VNDR_ID (+)
AND     T.VNDR_SUB_ID = S.VNDR_SUB_ID (+)
AND     T.TT_CODE = S.TT_CODE (+)
AND     T.TT_FREQ = S.TT_FREQ (+)
AND     T.TT_PYMT = S.TT_PYMT (+)
AND     T.TT_CFMD_CD = S.TT_CFMD_CD (+)
AND     T.RATE = S.RATE(+)
AND     T.PUR_TYPE = S.PUR_TYPE (+)
AND     T.ACCOUNT_DATE = S.ACCOUNT_DATE (+)
AND     T.ACCOUNT_DATE  BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE'
AND     (NVL(T.TRADE_AMOUNT,0) - NVL(S.TRADE_AMOUNT,0)) <> 0
UNION
SELECT  T.ACCOUNT_DATE,
        T.VNDR_ID,
        (SELECT TT_CSDCR FROM SMGR.TTCODE
		 WHERE TT_CODE||TT_FREQ||TT_PYMT=T.TT_CODE||T.TT_FREQ||T.TT_PYMT ) TT_DESCRIPTION, 
        NVL(T.TRADE_AMOUNT,0) - NVL(S.TRADE_AMOUNT,0) TRADE_AMOUNT
FROM    SMGR.ADJ_TRADE T,SMGR.TRADE_SNS S
WHERE   T.VNDR_ID = S.VNDR_ID (+)
AND     T.VNDR_SUB_ID = S.VNDR_SUB_ID (+)
AND     T.TT_CODE = S.TT_CODE (+)
AND     T.TT_FREQ = S.TT_FREQ (+)
AND     T.TT_PYMT = S.TT_PYMT (+)
AND     T.TT_CFMD_CD = S.TT_CFMD_CD (+)
AND     T.RATE = S.RATE(+)
AND     T.PUR_TYPE = S.PUR_TYPE (+)
AND     T.ACCOUNT_DATE = S.ACCOUNT_DATE (+)
AND     T.ACCOUNT_DATE  BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE'
AND     (NVL(T.TRADE_AMOUNT,0) - NVL(S.TRADE_AMOUNT,0)) <> 0
UNION
SELECT  T.ACCOUNT_DATE,
        T.VNDR_ID,
        (SELECT TT_CSDCR FROM SMGR.TTCODE
		 WHERE TT_CODE||TT_FREQ||TT_PYMT=T.TT_CODE||T.TT_FREQ||T.TT_PYMT ) TT_DESCRIPTION, 
        NVL(T.TRADE_AMOUNT,0) - NVL(S.TRADE_AMOUNT,0) TRADE_AMOUNT
FROM    SMGR.ACT_TRADE T,SMGR.TRADE_SNS S
WHERE   T.VNDR_ID = S.VNDR_ID (+)
AND     T.VNDR_SUB_ID = S.VNDR_SUB_ID (+)
AND     T.TT_CODE = S.TT_CODE (+)
AND     T.TT_FREQ = S.TT_FREQ (+)
AND     T.TT_PYMT = S.TT_PYMT (+)
AND     T.TT_CFMD_CD = S.TT_CFMD_CD (+)
AND     T.RATE = S.RATE(+)
AND     T.PUR_TYPE = S.PUR_TYPE (+)
AND     T.ACCOUNT_DATE = S.ACCOUNT_DATE (+)
AND     T.ACCOUNT_DATE  BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE'
AND     (NVL(T.TRADE_AMOUNT,0) - NVL(S.TRADE_AMOUNT,0)) <> 0
/
SPOOL OFF
/

/****************************************
 SHRINKAGE AND WASTEAGE BY STORE BY SKU EXPORT
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_017_SHRINKAGE_WASTAGE_BY_STORE_BY_SKU
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_017_SHRINKAGE_WASTAGE_BY_STORE_BY_SKU.CSV
SPOOL "&&V_FILENAME"
/
SELECT  MONTH, 
        BIG_KIND AS "CAT CODE", 
        AREA_SUB_ID AS "STORE CODE", 
        ITEM_CD AS "ITEM CODE", 
        SUM(REDUCE_TO_CLEAR) AS "REDUCE TO CLEAR", 
        SUM(WRITE_OFF) AS "WRITE OFF"
FROM
(
    SELECT  TO_CHAR(MD_DATE,'YYYYMM') AS "MONTH", 
            BIG_KIND, 
            AREA_SUB_ID, 
            ITEM_CD, 
            SUM(MD_VAL) AS "REDUCE_TO_CLEAR", 
            0 AS "WRITE_OFF"
    FROM SMGR.MD_D_ITEM D
    WHERE MD_DATE BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE' 
    AND CAT_CD IN ('R06')
    AND AREA_SUB_ID NOT IN (&&V_EXCLUDE_STORES_LIST)
    GROUP BY TO_CHAR(MD_DATE,'YYYYMM'), BIG_KIND, AREA_SUB_ID, ITEM_CD
    UNION
    SELECT  TO_CHAR(MD_DATE,'YYYYMM') AS "MONTH", 
            BIG_KIND, 
            AREA_SUB_ID, 
            ITEM_CD, 0 AS "REDUCE_TO_CLEAR", 
            SUM(MD_VAL) AS "WRITE_OFF"
    FROM SMGR.MD_D_ITEM D
    WHERE MD_DATE BETWEEN '&&V_BCG_STARTDATE' AND '&&V_BCG_ENDDATE' 
    AND CAT_CD IN ('F09')
    AND AREA_SUB_ID NOT IN (&&V_EXCLUDE_STORES_LIST)
    GROUP BY TO_CHAR(MD_DATE,'YYYYMM'), BIG_KIND, AREA_SUB_ID, ITEM_CD
) 
GROUP BY MONTH, BIG_KIND, AREA_SUB_ID, ITEM_CD
ORDER BY MONTH, BIG_KIND, AREA_SUB_ID, ITEM_CD
/
SPOOL OFF
/

/****************************************
 ALL NEW ITEMS (LESS THAN 3 MONTHS AFTER REVIEW END DATE) SKU ATTRIBUTES EXPORT
 INCLUDES CONCESS AND NON-CONCESS
 
 EXPORT FILE FORMAT: CSV
 EXPORT FILE NAME: BCG_018_ALL_NEW_ITEMS_EXPORT
 ****************************************/
SET SQLFORMAT CSV;
SET FEEDBACK OFF;
SET TERM OFF;
SET VERIFY OFF;
/
DEFINE V_FILENAME = &&V_OUTPUT_FOLDER\BCG_018_ALL_NEW_ITEMS_EXPORT.CSV
SPOOL "&&V_FILENAME"
/
SELECT I.ITEM_CD "SKU CODE",
       I.CREATE_DATE "CREATION DATE",
       I.CSHR_KIND "DEPT CODE",
       I.BIG_KIND "CAT CODE",
       I.ITEM_CNAME "SKU DESCRIPTION"
FROM SMGR.ITEM I
LEFT JOIN SMGR.COUNTRY_M CM ON CM.COUNTRY_CD=I.ITEM_CHAR
WHERE LENGTH(I.ITEM_CD)='6'
AND I.CREATE_DATE > '&&V_BCG_ENDDATE' 
AND I.CREATE_DATE <= ADD_MONTHS('&&V_BCG_ENDDATE',&&V_NEW_ITEM_MONTHS)
UNION ALL
SELECT  I.ITEM_CD "SKU CODE",
        I.CREATE_DATE "CREATION DATE",
        I.CSHR_KIND "DEPT CODE",
        I.BIG_KIND "CAT CODE",
        I.DESCRIPTION "SKU DESCRIPTION"
FROM SMGR.ITEM_DEPT I
WHERE LENGTH(ITEM_CD)='6'
AND I.CREATE_DATE > '&&V_BCG_ENDDATE' 
AND I.CREATE_DATE <= ADD_MONTHS('&&V_BCG_ENDDATE',&&V_NEW_ITEM_MONTHS)
/
SPOOL OFF
/